### ISSUE TITLE
Creating a structure like a LiteDeviceDelegatingViewResolver with a ViewResolver per Strategy

### ISSUE THREAD

**Issue by dgomesbr** [spring-projects/spring-mobile#14]
The issue addressed in #7 is very good for systems that use one viewResolver for all.

I'm currently facing this scenario:

HTML5 for web/touch devices and desktops, which uses a ThymeleafViewResolver with contentType set to:

```
"text/html; charset=UTF-8"
```

and XHTML for feature phones using another ThymeleafViewResolver with contentType set to:

```
"aplication/xml; charset=UTF-8"
```

So I have _pages/html/home.html_ and _pages/xhtml/home.xhtml_, since they both points to same _viewResolver_ I can't use this strategy, and there's another problem and thats on _thymeleaf_ side, how to resolve the correct template based on the device type (I'll probably try to create an extension for them), should I create this structure on my side and then pull request it here?

**Comment by royclarkson** [comment]
Appears that thymeleaf has made some improvements to handle this.
