### ISSUE TITLE
Detection systems provide

### ISSUE THREAD

**Issue by hwtl** [spring-projects/spring-mobile#24]
Whether DeviceUtils can provide a way to check the phone system, the system returns an enumeration
ios, mac ox, android, etc., or else we'll get from the inside UserAgent
thank you

**Comment by cemo** [comment]
@royclarkson It would be a nice feature. 

+1

**Comment by pasali** [comment]
+1

**Comment by royclarkson** [comment]
fyi, 1.1.4.RELEASE is published with @okohub's contribution.
