### ISSUE TITLE
New Structure For Device and Device Resolving

### ISSUE THREAD

**Issue by okohub** [spring-projects/spring-mobile#26]
Hi @royclarkson,

Regarding to issue #25, I want to talk about what we can do more. 

1) As you said we should make this process modular, where people can register several strategies within the DeviceResolver. What are you thinking about that, what is the way we should follow? I want to help.

Moreover, I think Device interface would share more information, let's make it more robust and powerful by designing with 3 dimension; DeviceType - DevicePlatform - DeviceChannel.

You know we already handled DeviceType and DevicePlatform, but DeviceType is not accessible. We should add getter for this. 

DeviceChannel is new, this dimension will identify the channel of user. For example, it is not certain that a MOBILE - IOS user is entering from a browser. May be user is coming from a mobile application. I think we can also handle it using a custom http header?

2) With upgrades, I think there should be a new simple module that only contains device and device resolving. This will also help people who only want to use Device Resolving. (especially in spring-boot)

**Comment by okohub** [comment]
ping @royclarkson

**Comment by royclarkson** [comment]
My thoughts are to create an interface for the strategy. Perhaps name it `DeviceResolverRule`, or something similar. `LiteDeviceResolver` could then accept a `List<DeviceResolverRule>` in a setter or a constructor. Then `resolveDevice` would run through all those rules and return a `Device` when one is matched. If the rule doesn't match it could return null. We need to think about that. 

There needs to be a way to set an order of processing or priority for the rules. A simple approach is to process in the order of the list. Obviously, all current tests should pass after these changes are made too. An initial set of rules should be defined by the commented sections, such as Normal, Tablet, UAProf, User-Agent prefix, etc.

I don't understand what `DeviceChannel` would provide that you don't get from the other properties. Can you elaborate? One thing to keep in mind is that some people may be using Spring Mobile with something like DeviceAtlas or WURFL, so the interface needs to make sense for other implementations too.

**Comment by royclarkson** [comment]
If we were to break up the modules, that would likely need to be a major release (2.0), since that's a significant change.

**Comment by ccit-spence** [comment]
@royclarkson @okohub Are there any thoughts on handling of high resolution devices like the iPhone 6 plus and iPad Retinas?  Would it be as simple as modifying the `LiteDeviceResolver` essentially providing more choices that just `phone`, `tablet`, `desktop`?  The interface would be a decent way to extend the functionality to provide the granularity for those that want to turn it on.

**Comment by royclarkson** [comment]
Short answer is yes, the `LiteDeviceResolver` can be extended to include more device types. That's simple enough, but the issue is always going to be how to differentiate device types based on user agent in a generic manner. Additionally, Apple, Google, and Microsoft seem to continue to discourage this practice because their small screen browsers are just as capable as the larger screens. Feel free to reopen, or create a new issue if you have a contribution. Thanks.
