### ISSUE TITLE
Bot User-Agent conflicting with KNOWN_MOBILE_USER_AGENT_PREFIXES

### ISSUE THREAD

**Issue by Noki** [spring-projects/spring-mobile#30]
Hi!

We operate a web crawler that performs technical audits for a number of clients. Some of our clients use the Spring Framework and the spring-mobile extension to detect mobile user-agents.

The prefix "audi" in the list of known mobile user agent prefixes conflicts with the user-agent of our bot. 

```
private static final String[] KNOWN_MOBILE_USER_AGENT_PREFIXES = new String[] {
        "w3c ", "w3c-", "acs-", "alav", "alca", "amoi", "audi", "avan", "benq",
        "bird", "blac", "blaz", "brew", "cell", "cldc", "cmd-", "dang", "doco",
        "eric", "hipt", "htc_", "inno", "ipaq", "ipod", "jigs", "kddi", "keji",
        "leno", "lg-c", "lg-d", "lg-g", "lge-", "lg/u", "maui", "maxo", "midp",
        "mits", "mmef", "mobi", "mot-", "moto", "mwbp", "nec-", "newt", "noki",
        "palm", "pana", "pant", "phil", "play", "port", "prox", "qwap", "sage",
        "sams", "sany", "sch-", "sec-", "send", "seri", "sgh-", "shar", "sie-",
        "siem", "smal", "smar", "sony", "sph-", "symb", "t-mo", "teli", "tim-",
        "tosh", "tsm-", "upg1", "upsi", "vk-v", "voda", "wap-", "wapa", "wapi",
        "wapp", "wapr", "webc", "winw", "winw", "xda ", "xda-" };
```

Our user-agent starts with "audisto.com" and is therefore always identified as mobile user-agent. 

```
audisto.com full crawler 3.25.423 (refer to in robots.txt as audisto, see https://audisto.com/bot)
```

More information about our bot can be found here: https://audisto.com/help/crawler/bot

We would welcome an improved mobile detection in the spring framework especially because it usually affects new customers that are not aware of this issue. Due to our large user base and implication on other 3rd party software we can not change the user-agents of our bot.

Best Regards
Tobias

**Comment by gerdriesselmann** [comment]
The prefix in question tries to match the AUDIOVOX-SMT5600  mobile phone browser. This phone was last manufactured in 2005 and can be considered to not be in use any more. 

I therefore suggest to simply remove the prefix "audi".

**Comment by royclarkson** [comment]
It is possible with the current release to [override](http://docs.spring.io/spring-mobile/docs/1.1.4.RELEASE/reference/html/device.html#device-resolvers) the default behavior and force certain keywords to resolve to a "normal" device. For example, you could set "audi" as "normal" user-agent keyword.

**Comment by hathead** [comment]
Since the checking algorithm is based on Wordpress Mobile Pack from 2010 it should be considered to rewrite it completely.

**Comment by Noki** [comment]
@royclarkson: I am aware that you can override the default behavior, however this is only the fix once you become aware that the default behavior is broken and the checks are outdated. I suggest you take a look at the  Mobiledetect project (http://mobiledetect.net/), which has a much better approach to detect mobile devices. They also have a large number of tests you might want to adapt: https://github.com/serbanghita/Mobile-Detect/blob/master/tests/ualist.json

**Comment by gerdriesselmann** [comment]
I was able to trace the four-letter-prefix-array back until 2007, when it appeared in the book "Mobile Web Design" by Camaron Moll. I'm sure however, the code is even older. 

This book deals with WAP 2.0, which was obsoleted in the same year by the first iPhone. And the whole purpose of the detection code was to detect *WAP-browsers*.

Detecting WAP-browsers does not make sense in 2016 any more. I therefore second @hathead: this code would need a complete overhaul.

But as for now, simply removing the "audi" prefix would make things a lot better.
