### ISSUE TITLE
SAMSUNG I9308 mobile , Device incorrect

### ISSUE THREAD

**Issue by venusdrogon** [spring-projects/spring-mobile#32]
our tester use `SAMSUNG I9308` mobile test our website

but  `currentDevice` result is `tablet`

`user-agent` is:

```
SAMSUNG-GT-I9308_TD/1.0 Android/4.1.2 Release/12.20.2012 Browser/AppleWebKit534.30
```

I review `org.springframework.mobile.device.LiteDeviceResolver.resolveDevice(HttpServletRequest)`method

because `user-agent`

`userAgent.contains("android") && !userAgent.contains("mobile")`  so return `tablet`

but the device actual is `mobile` not `tablet`

**Comment by royclarkson** [comment]
Thanks for reporting! The dilemma is that Google says to [look for the `mobile` keyword](https://developer.chrome.com/multidevice/user-agent) in user-agent strings.
