### ISSUE TITLE
iOS13 iPad User Agent Issue

### ISSUE THREAD

**Issue by coreyoss** [spring-projects/spring-mobile#48]
iPads on iOS13 will, by default, include a user-agent that matches MacOS, which breaks tablet detection in LiteDeviceResolver.java. This seems like an Apple issue, and I don't know that there is anything that can be done on the Spring side, but I thought I'd ask -

Does Spring Mobile have any plans to address this?

**Comment by royclarkson** [comment]
Hi @coreyoss, Thanks for reaching out. Spring Mobile is currently not being maintained. In general the industry now favors a responsive UI design over redirecting to separate web sites via server-side device detection. Additionally, the browser venders are more actively discouraging this practice. Microsoft did this a few years ago, and now Apple is defaulting to identical user agents in iPadOS/iOS/macOS.
