### ISSUE TITLE
Status of the project?

### ISSUE THREAD

**Issue by leonard84** [spring-projects/spring-mobile#49]
The current Milestone `2.0.0 M3` was released on 26. Mar 2018. Is there anything that prevents a final 2.0 release, so that the artifact is available in Maven Central?
Is the lack of activity caused by it just working, or is this project abandoned/dormant?

**Comment by royclarkson** [comment]
Hi @leonard84. Thanks for reaching out. Spring Mobile is currently not being maintained. The functionality has been basically the same for many years and works as intended. The 2.0 milestones were published to support Java 8, Spring Boot 2, and Spring Framework 5. Spring Boot 2 removed Spring Mobile auto-configuration support, so we published the starter as independent artifacts from the Spring Mobile project instead. We wanted the community to continue to be able to use the project if they desired. You can see these notes in the release history. In general the industry now favors a responsive UI design over utilizing server-side device detection to produce separate web sites. Additionally, the browser venders are more actively discouraging this practice.
